---
abstract: 'package for digestarchive command'
author:
  - 'Akira Horimoto <emperor.kurt _at_ gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-digestarchive
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor: 0.34
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/holly/perl-App-digestarchive.git
version: 0.03
